INSERT INTO public.categoria (id,icone,id_categoria_pai,nome) VALUES
(41,'',1,'Medico')
,(7,'',1,'Técnico de enfermagem')
,(8,'',1,'Outros')
,(9,'',1,'Fonoaudiólogo')
,(10,'',1,'Fisioterapeuta(o)')
,(12,'',2,'Serralheiro')
,(13,'',2,'Mestre de obras')
,(14,'',2,'Marceneiro')
;
INSERT INTO public.categoria (id,icone,id_categoria_pai,nome) VALUES
(15,'',2,'Engenheiro')
,(16,'',2,'Pedreiro')
,(17,'',2,'Gesseiro')
,(18,'',2,'Pintor')
,(19,'',2,'outros')
,(20,'',3,'Computador/Notebook')
,(21,'',3,'Televisores')
,(22,'',3,'Outros')
,(23,'',3,'Segurança Eletrônica')
,(24,'',3,'Celular')
;
INSERT INTO public.categoria (id,icone,id_categoria_pai,nome) VALUES
(25,'',4,'Técnico de informática')
,(26,'',4,'Técnico de rede')
,(27,'',4,'Segurança da informação')
,(28,'',4,'Analista')
,(29,'',4,'Outros')
,(30,'',4,'Desenvolvedor de software')
,(32,'',5,'Moto')
,(33,'',5,'Bicicleta')
,(34,'',5,'Outros')
,(35,'',5,'Ônibus/caminhão')
,(36,'',5,'Carro')
,(37,'',6,'Domestica')
,(38,'',6,'Cozinheira(o)')
,(39,'',6,'Garçom/Garçonete')
,(40,'',6,'Outros')
;
INSERT INTO public.categoria (id,icone,id_categoria_pai,nome) VALUES
(4,'logo-windows',0,'Informática')
,(2,'hammer',0,'Construção')
,(5,'construct',0,'Mecânica')
,(1,'pulse',0,'Área medica')
,(3,'flash',0,'Eletrônica')
,(6,'home',0,'Para você/casa')
;